Fix initialization bug introduced in #2960 (#3006)
* Fix initialization bug introduced in #2960

The quantized adalora SVD layers were not initialized in the new
config-passing scheme and therefore raised errors in the GPU
tests.

For reproduction run

```
make tests_examples_single_gpu
```

which will yield

```
FAILED tests/test_gpu_examples.py::PeftBnbGPUExampleTests::test_4bit_adalora_causalLM - TypeError: SVDLinear4bit.__init__() missing 1 required positional argument: 'config'
FAILED tests/test_gpu_examples.py::PeftBnbGPUExampleTests::test_8bit_adalora_causalLM - TypeError: SVDLinear8bitLt.__init__() missing 1 required positional argument: 'config'
```

* Fix a small error with pytorch 2.10

Now it seems that a ValueError is raised indicating that the lora linear implementation
only supports 8 bit for now.

---------

Co-authored-by: nemo <git@ningu.net>