FIX Truncate slack message to not exceed 3000 char (#1251)
Should fix the issue of not receiving slack notifications because the
message is too long, see:

https://github.com/huggingface/peft/actions/runs/7148379741/job/19469273483

Currently, we get:

> Error: ver responded with: {'ok': False, 'error': 'invalid_blocks', 'errors': ['failed to match all allowed schemas [json-pointer:/blocks/1/text]', 'must be less than 3001 characters [json-pointer:/blocks/1/text/text]'], 'response_metadata': {'messages': ['[ERROR] failed to match all allowed schemas [json-pointer:/blocks/1/text]', '[ERROR] must be less than 3001 characters [json-pointer:/blocks/1/text/text]']}}

Fixing the error should also lead to a shorter message, but we should
ensure that even if the message is too long, we still get it.