Ensure that te.pytorch exists (#3081)
It's possible to install transformer_engine without the pytorch option which will break the TE integration in the LoRA tuner since `transformer_engine.pytorch` doesn't exist.

This is a minor annoyance but since I stumbled upon it I think it is better fixed than left open.

Reproduction:

```
$ pip install transformer_engine[core]

# run PEFT unit tests, for example, observe error:

---
        if is_te_available() and isinstance(                                                                                                                          
>           target_base_layer, (te.pytorch.LayerNormLinear, te.pytorch.LayerNormMLP, te.pytorch.Linear)                                                               
                                ^^^^^^^^^^                                                                                                                            
        ):                                                                                                                                                            
E       AttributeError: module 'transformer_engine' has no attribute 'pytorch'                                                                                        
---
```

Once you install `transformer_engine[pytorch]` the error disappears.

* Add TE to the GPU docker file
* Use CUDNN docker image (TE requirement)

---------

Co-authored-by: nemo <git@ningu.net>