Allow passing inputs_embeds instead of input_ids
Resolves #727

Right now, there is an issue with a few PeftModelForXxx classes when
users pass only inputs_embeds but not input_ids. First of all, the batch
size was being derived on input_ids, now it is derived from
inputs_embeds instead if input_ids is None. Furthermore, a few forward
calls to the base model were not passing the inputs_embeds along, which
resulted in errors down the line. These issues have been fixed now.

During testing, I ran into a some problems.

1. For decoder models, the test would fail for GPTBigCodeForCausalLM.
   I'm not sure why, but that model is already excluded in another test, so
   I just excluded it for this test too.

2. For feature extraction tests, the test would fail for prefix tuning.
   Not sure exactly why. I thought I only needed pass the inputs_embeds
   to the self.base_model call for prefix tuning, but then I got the error

> TypeError: DebertaV2Model.forward() got an unexpected keyword argument
'past_key_values'

   Therefore, I just excluded those tests for the time being.

3. Similarly, I wanted to add the tests to encoder-decoder models, but
   there I got the error:

> ValueError: If no `decoder_input_ids` or `decoder_inputs_embeds` are
passed, `input_ids` cannot be `None`. Please pass either `input_ids` or
`decoder_input_ids` or `decoder_inputs_embeds`.

   So now, the tests are not run for encoder-decoder.

It would be great if someone else with more expertise could ensure that
those cases work correctly.