Ignore BPE errors in tests
We're seeing deprecation warnings from BPE, used by transformers:

    FAILED tests/test_gpu_examples.py::PeftBnbGPUExampleTests::test_causal_lm_training_4bit_vera - DeprecationWarning: Deprecated in 0.9.0: BPE.__init__ will not create from files anymore, try `BPE.from_file` instead
    FAILED tests/test_gpu_examples.py::PeftBnbGPUExampleTests::test_causal_lm_training_8bit_dora - DeprecationWarning: Deprecated in 0.9.0: BPE.__init__ will not create from files anymore, try `BPE.from_file` instead

Since we can't do anything about it and it is not a direct transformers deprecation,
we can ignore it.