FIX CPT no tested with sequence classification
PR #2481 added sequence classification tests to PEFT. The test matrix
included CPT. However, CPT only supports the task type CAUSAL_LM. These
tests still passed but now started failing with:

> AttributeError: object has no attribute 'prepare_inputs_for_generation'

This is probably a change in transformers but the since causal LM was
never meant to work, the actual fix is to remove CPT from the seq cls
test matrix.

Since CPT automatically changes the task type to CAUSAL_LM, this mistake
can be hard to spot. Therefore, this PR also adds a warning if users
pass the wrong task type.