CI Update AutoAWQ version to fix CI
Currently, the CI fails because awq tries to import a non-existing
function from transformers (presumably it was there at one point but no
longer is):

>     from transformers.modeling_utils import shard_checkpoint
> E   ImportError: cannot import name 'shard_checkpoint' from 'transformers.modeling_utils' (/opt/conda/envs/peft/lib/python3.11/site-packages/transformers/modeling_utils.py)

This has been fixed in awq v0.2.7. Therefore, this newer version is now
used in CI.